/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Coursework;

import org.junit.Test;
import static org.junit.Assert.*;

public class Dec2HexTest {
    @Test public void validateInput() {
        assertEquals("2", Dec2Hex.Convert(new String[]{"2"}));
        assertEquals("F", Dec2Hex.Convert(new String[]{"15"}));
        assertEquals("25", Dec2Hex.Convert(new String[]{"19"}));
        assertEquals("4000", Dec2Hex.Convert(new String[]{"FA0"}));
        assertEquals("8400", Dec2Hex.Convert(new String[]{"20D0"}))
    }

    @Test public void validNumber(){
        assertTrue(Dec2Hex.validInput("1"));
        assertTrue(Dec2Hex.validInput("84"));
        assertTrue(Dec2Hex.validInput("0"));

        assertFalse(Dec2Hex.validInput("-1"));
        assertFalse(Dec2Hex.validInput("-84"));
        assertFalse(Dec2Hex.validInput("-72"));
}

}
